
IF DB_ID(N'SalesOrderManagement') IS NULL
BEGIN
	CREATE DATABASE SalesOrderManagement;
END;
GO

USE SalesOrderManagement;
GO

IF OBJECT_ID(N'dbo.COM_CUSTOMER', N'U') IS NULL
BEGIN
	CREATE TABLE dbo.COM_CUSTOMER
	(
		COM_CUSTOMER_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_COM_CUSTOMER PRIMARY KEY,
		CUSTOMER_NAME VARCHAR(100) NOT NULL
	);
END;
GO

IF OBJECT_ID(N'dbo.SALES_SO', N'U') IS NULL
BEGIN
	CREATE TABLE dbo.SALES_SO
	(
		SALES_SO_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_SALES_SO PRIMARY KEY,
		SO_NO VARCHAR(20) NOT NULL CONSTRAINT UQ_SALES_SO_SO_NO UNIQUE,
		ORDER_DATE DATETIME NOT NULL,
		COM_CUSTOMER_ID INT NOT NULL,
		ADDRESS VARCHAR(500) NULL,
		CONSTRAINT FK_SALES_SO_CUSTOMER FOREIGN KEY (COM_CUSTOMER_ID) REFERENCES dbo.COM_CUSTOMER(COM_CUSTOMER_ID)
	);
END;
GO

IF OBJECT_ID(N'dbo.SALES_SO_LITEM', N'U') IS NULL
BEGIN
	CREATE TABLE dbo.SALES_SO_LITEM
	(
		SALES_SO_LITEM_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_SALES_SO_LITEM PRIMARY KEY,
		SALES_SO_ID INT NOT NULL,
		ITEM_NAME VARCHAR(100) NOT NULL,
		QUANTITY INT NOT NULL,
		PRICE FLOAT NOT NULL,
		CONSTRAINT FK_SALES_SO_LITEM_SO FOREIGN KEY (SALES_SO_ID) REFERENCES dbo.SALES_SO(SALES_SO_ID)
	);
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.COM_CUSTOMER WHERE CUSTOMER_NAME = 'PT Maju Bersama')
	INSERT dbo.COM_CUSTOMER (CUSTOMER_NAME) VALUES ('PT Maju Bersama');
IF NOT EXISTS (SELECT 1 FROM dbo.COM_CUSTOMER WHERE CUSTOMER_NAME = 'CV Sejahtera Abadi')
	INSERT dbo.COM_CUSTOMER (CUSTOMER_NAME) VALUES ('CV Sejahtera Abadi');
IF NOT EXISTS (SELECT 1 FROM dbo.COM_CUSTOMER WHERE CUSTOMER_NAME = 'PT Karya Utama')
	INSERT dbo.COM_CUSTOMER (CUSTOMER_NAME) VALUES ('PT Karya Utama');
GO

IF NOT EXISTS (SELECT 1 FROM dbo.SALES_SO WHERE SO_NO = 'SO-2026-0001')
BEGIN
	INSERT dbo.SALES_SO (SO_NO, ORDER_DATE, COM_CUSTOMER_ID, ADDRESS)
	VALUES ('SO-2026-0001', '2026-08-01',
			(SELECT TOP 1 COM_CUSTOMER_ID FROM dbo.COM_CUSTOMER WHERE CUSTOMER_NAME = 'PT Maju Bersama'),
			'Jakarta');
	INSERT dbo.SALES_SO_LITEM (SALES_SO_ID, ITEM_NAME, QUANTITY, PRICE)
	VALUES (SCOPE_IDENTITY(), 'Laptop Business', 2, 12500000);
END;
GO
